### ISSUE TITLE
关于Qwen2idae的训练问题

### ISSUE THREAD

**Issue by Yu-Yang-Li** [wuhy68/Parameter-Efficient-MoE#8]
感谢您之前的解答，基于已有数据，我们尝试训练了他山模型：
https://www.modelscope.cn/models/AstroYuYang/TaShan-8x34B

当前阶段，我们对于Qwen2idae的训练很感兴趣，但好像并没有看到相关代码的提交，github中仍然是Camelidae模型。
想请问，训练的时候是否只需要更改代码中的configuration和modeling为Qwen2idae对应的文件，就可以成功复现训练吗？
或者是否方便上传Qwen2idae系列的代码。

Thanks♪(･ω･)ﾉ

**Comment by wuhy68** [comment]
是的，只需要更改代码中的configuration和modeling为Qwen2idae对应的文件就可以训练。需要注意升级到Qwen2对应的transformers版本。

**Comment by Yu-Yang-Li** [comment]
> 是的，只需要更改代码中的configuration和modeling为Qwen2idae对应的文件就可以训练。需要注意升级到Qwen2对应的transformers版本。

修改文件后,开始训练报错...
```python
You are using a model of type qwen2 to instantiate a model of type qwen2idae. This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "/root/LLM/Parameter-Efficient-MoE/train_scripts/train_moe.py", line 450, in <module>
    train()
  File "/root/LLM/Parameter-Efficient-MoE/train_scripts/train_moe.py", line 444, in train
    trainer.train()
  File "/root/anaconda3/envs/moe/lib/python3.11/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/moe/lib/python3.11/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/moe/lib/python3.11/site-packages/transformers/trainer.py", line 2781, in training_step
    self.accelerator.backward(loss)
  File "/root/anaconda3/envs/moe/lib/python3.11/site-packages/accelerate/accelerator.py", line 1905, in backward
    loss.backward(**kwargs)
  File "/root/anaconda3/envs/moe/lib/python3.11/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/root/anaconda3/envs/moe/lib/python3.11/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/anaconda3/envs/moe/lib/python3.11/site-packages/torch/autograd/function.py", line 289, in apply
    return user_fn(self, *args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/moe/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 275, in backward
    tensors = ctx.saved_tensors
              ^^^^^^^^^^^^^^^^^
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [CUDABFloat16Type [1, 1, 398, 398]] is at version 41; expected version 39 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

**Comment by Yu-Yang-Li** [comment]
问题解决，是pytorch版本问题 2.0.0可以正常运行
